### PR TITLE
Use print as a function for Python3, md5 and os are unsused

### PR DESCRIPTION
**Pull request by moyogo**

### CODE REVIEW

**Comment by behdad** [comment]
I see md5 used.

**Comment by anthrotype** [comment]
well, I can't see md5 used anywhere else than in that import statement.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ git grep md5
fontcrunch/fontcrunch.py:import md5
```

**Comment by moyogo** [comment]
Where is md5 used?
If it is, it should be replaced by hashlib.md5 (md5 is deprecated since python 2.5 https://docs.python.org/2/library/md5.html)

**Comment by behdad** [comment]
Sorry I was checking the wrong branch (my fork).

Originally md5 was used because the Python layer was writing beziers to files and then run the C++ code on it.  That had two benefits: duplicate curve segments were optimized only once, and the C++ portion could be run on multiple cores.

Now, looks like that has been replaced by a CPython module wrapping the C++ code.  That probably takes away the multi-core capability.  But someone needs to check that we don't try to optimize identical curve segments multiple times.

**Comment by khaledhosny** [comment]
I think we should just merge this, it is easy to restore md5 if it is needed again in the future.

**Comment by behdad** [comment]
Sure.

**Comment by khaledhosny** [comment]
Merged manually.

**Pull request closed without merging**
